### ISSUE TITLE
Analytics command is broken now

### ISSUE THREAD

**Issue by dchaplinsky** [dchaplinsky/declarations.com.ua#42]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/var/www/venv/lib/python3.4/site-packages/django/core/management/**init**.py", line 385, in execute_from_command_line
    utility.execute()
  File "/var/www/venv/lib/python3.4/site-packages/django/core/management/**init**.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/www/venv/lib/python3.4/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(_args, *_options.**dict**)
  File "/var/www/venv/lib/python3.4/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(_args, *_options)
  File "/var/www/declarations.com.ua/declarations_site/catalog/management/commands/analytics.py", line 38, in handle
    table = self._generate_table(all_decls)
  File "/var/www/declarations.com.ua/declarations_site/catalog/management/commands/analytics.py", line 61, in _generate_table
    decl_dict = self._map_fields(decl)
  File "/var/www/declarations.com.ua/declarations_site/catalog/management/commands/analytics.py", line 91, in _map_fields
    'family_num': len(declaration.general.family_raw.split(';')) if declaration.general.family_raw else 0,
  File "/var/www/venv/lib/python3.4/site-packages/elasticsearch_dsl/utils.py", line 405, in __getattr__
    return super(ObjectBase, self).**getattr**(name)
  File "/var/www/venv/lib/python3.4/site-packages/elasticsearch_dsl/utils.py", line 109, in **getattr**
    '%r object has no attribute %r' % (self.**class**.**name**, attr_name))
AttributeError: 'InnerObjectWrapper' object has no attribute 'family_raw'

**Comment by excieve** [comment]
Should be fixed by 9ae5a6975f23b4ade47ec3730e9b63bee7236e14

**Comment by dchaplinsky** [comment]
Should I also reimport latest batch?

**Comment by dchaplinsky** [comment]
(venv)root@declarations:/var/www/declarations.com.ua/declarations_site# ./manage.py analytics
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/var/www/venv/lib/python3.4/site-packages/django/core/management/**init**.py", line 385, in execute_from_command_line
    utility.execute()
  File "/var/www/venv/lib/python3.4/site-packages/django/core/management/**init**.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/www/venv/lib/python3.4/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(_args, *_options.**dict**)
  File "/var/www/venv/lib/python3.4/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(_args, *_options)
  File "/var/www/declarations.com.ua/declarations_site/catalog/management/commands/analytics.py", line 38, in handle
    table = self._generate_table(all_decls)
  File "/var/www/declarations.com.ua/declarations_site/catalog/management/commands/analytics.py", line 61, in _generate_table
    decl_dict = self._map_fields(decl)
  File "/var/www/declarations.com.ua/declarations_site/catalog/management/commands/analytics.py", line 160, in _map_fields
    'other_space': sum(estate_space(declaration.estate['28'])),
  File "/var/www/declarations.com.ua/declarations_site/catalog/management/commands/analytics.py", line 74, in estate_space
    for e in estate if e['space']]
  File "/var/www/declarations.com.ua/declarations_site/catalog/management/commands/analytics.py", line 74, in <listcomp>
    for e in estate if e['space']]
TypeError: string indices must be integers

:-\

**Comment by excieve** [comment]
@dchaplinsky you should drop the index and then reimport everything as old records have issues in the data.
